# docker build . -t chaincue-real-estate-go
# docker compose -f docker-compose-test-go-app.yml up

version: '3.9'

services:
  chaincue-real-estate-go:
    container_name: chaincue-real-estate-go
    image: chaincue-real-estate-go:latest
    ports:
      - "8080:8080"
    networks:
      - chaincue-real-estate-network

networks:
  chaincue-real-estate-network:
    driver: bridge
    name: chaincue-real-estate-network
