apiVersion: v1
kind: ConfigMap
metadata:
  name: chaincue-real-estate-config
data:
  CORS_ALLOW_ORIGINS: "http://localhost:3000"
  OAUTH_CLIENT_ID: "real-estate-client"
  OAUTH_CLIENT_SECRET: "secret"
  OAUTH_AUTH_URL: "https://auth.chaincuet.com/auth/realms/real-estate/protocol/openid-connect/auth"
  OAUTH_TOKEN_URL: "https://auth.chaincuet.com/auth/realms/real-estate/protocol/openid-connect/token"
  OAUTH_INTROSPECT_URL: "https://auth.chaincuet.com/auth/realms/real-estate/protocol/openid-connect/token/introspect"
  POSTGRES_HOST: "10.244.0.57" # IP
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "chaincue-real-estate-postgres"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin"
  REDIS_HOST: "10.98.176.68" # Cluster IP
  REDIS_PASSWORD: "redis"
  REDIS_PORT: "6379"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaincue-real-estate-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaincue-real-estate-go
  template:
    metadata:
      labels:
        app: chaincue-real-estate-go
    spec:
      containers:
        - name: chaincue-real-estate-go
          image: chaincue-real-estate-go:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: chaincue-real-estate-config
---

apiVersion: v1
kind: Service
metadata:
  name: chaincue-real-estate-go
spec:
  selector:
    app: chaincue-real-estate-go
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chaincue-real-estate-go-ingress
spec:
  rules:
    - host: local.chaincue.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chaincue-real-estate-go
                port:
                  number: 8080
